import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import { Suspense } from "react";
import Loading from "./loading";

const myFont = localFont({
  src: "../../public/NotoSansLao_Condensed-Black.ttf"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>

      <body
        className={myFont.className}
      >
        <Suspense fallback={<Loading />}>
          <StackProvider app={stackServerApp}><StackTheme>
            <Header></Header>
            {children}
            <footer className="relative bg-gradient-to-r from-[#205781] to-gray-300 h-16 row-start-3 flex gap-6 flex-wrap items-center justify-center ">

            </footer>
          </StackTheme></StackProvider>
        </Suspense>
      </body>
    </html>
  );
}
