import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";

const myFont = localFont({
  src: "../../public/NotoSansLao_Condensed-Black.ttf"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>

      <body
        className={myFont.className}
      >
                <Header></Header>
        {children}
      </body>
    </html>
  );
}
